[build]
dockerfilePath = "juntos-alpha/Dockerfile"
context = "."

[deploy]
startCommand = "java -jar app.jar"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.environment]
SERVER_ADDRESS = "0.0.0.0"