[build]
builder = "docker"
dockerfilePath = "juntos-alpha/Dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.environment]
PORT = "8080"
SERVER_PORT = "8080"