spring:
  application:
    name: falcon-alpha
  datasource:
    url: jdbc:postgresql://localhost:5432/falcon
    username: postgres
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    app.falcon: INFO
