apiVersion: v1
kind: Service
metadata:
  name: juntos-alpha
  namespace: juntos
  labels:
    app: juntos-alpha
spec:
  type: LoadBalancer
  selector:
    app: juntos-alpha
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
